name: Update README with Latest Medium Blogs

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Blog Post Workflow
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@KavindhyaSammani"
